name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Images
      run: docker compose -f udacity-c3-deployment/docker/docker compose-build.yaml build --parallel
